// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setuserChirpyRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setUserChirpyRed = `-- name: SetUserChirpyRed :exec
update users
set is_chirpy_red =$2
where id = $1
`

type SetUserChirpyRedParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

func (q *Queries) SetUserChirpyRed(ctx context.Context, arg SetUserChirpyRedParams) error {
	_, err := q.db.ExecContext(ctx, setUserChirpyRed, arg.ID, arg.IsChirpyRed)
	return err
}
